/* 
 * SCOIR API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Identified struct {

	// Id is assigned when the score is created
	Id string `json:"Id,omitempty"`
}
