/* 
 * SCOIR API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Sat struct {

	// Id is assigned when the score is created
	Id string `json:"Id,omitempty"`

	// UpdatedBy is managed by SCOIR
	UpdatedBy string `json:"UpdatedBy,omitempty"`

	// UpdatedAt is managed by SCOIR
	UpdatedAt string `json:"UpdatedAt,omitempty"`

	TestDate string `json:"TestDate"`

	MathScore int32 `json:"MathScore"`

	ReadingScore int32 `json:"ReadingScore"`

	WritingScore int32 `json:"WritingScore"`

	EssaySubscore int32 `json:"EssaySubscore,omitempty"`

	WritingMCSubscore int32 `json:"WritingMCSubscore,omitempty"`
}
