/* 
 * SCOIR API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Sat2016 struct {

	// Id is assigned when the score is created
	Id string `json:"Id,omitempty"`

	// UpdatedBy is managed by SCOIR
	UpdatedBy string `json:"UpdatedBy,omitempty"`

	// UpdatedAt is managed by SCOIR
	UpdatedAt string `json:"UpdatedAt,omitempty"`

	TestDate string `json:"TestDate"`

	MathScore int32 `json:"MathScore"`

	ReadingAndWritingScore int32 `json:"ReadingAndWritingScore"`

	ReadingTestScore int32 `json:"ReadingTestScore,omitempty"`

	WritingAndLanguageScore int32 `json:"WritingAndLanguageScore,omitempty"`

	MathTestScore int32 `json:"MathTestScore,omitempty"`

	AnalysisInScience int32 `json:"AnalysisInScience,omitempty"`

	AnalysisInHistory int32 `json:"AnalysisInHistory,omitempty"`

	WordsInContext int32 `json:"WordsInContext,omitempty"`

	CommandOfEvidence int32 `json:"CommandOfEvidence,omitempty"`

	ExpressionOfIdeas int32 `json:"ExpressionOfIdeas,omitempty"`

	EnglishConventions int32 `json:"EnglishConventions,omitempty"`

	HeartOfAlgebra int32 `json:"HeartOfAlgebra,omitempty"`

	AdvancedMathematics int32 `json:"AdvancedMathematics,omitempty"`

	ProblemSolvingData int32 `json:"ProblemSolvingData,omitempty"`

	EssayReadingSubscore int32 `json:"EssayReadingSubscore,omitempty"`

	EssayAnalysisSubscore int32 `json:"EssayAnalysisSubscore,omitempty"`

	EssayWritingSubscore int32 `json:"EssayWritingSubscore,omitempty"`
}
