/* 
 * SCOIR API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Updatable struct {

	// UpdatedBy is managed by SCOIR
	UpdatedBy string `json:"UpdatedBy,omitempty"`

	// UpdatedAt is managed by SCOIR
	UpdatedAt string `json:"UpdatedAt,omitempty"`
}
